sudo: false
language: erlang
notifications:
  email: maximfca@gmail.com
otp_release:
  - 23.0
  - 22.0
  - 21.2
script: "wget https://s3.amazonaws.com/rebar3/rebar3 && escript rebar3 do ct"
branches:
  only:
    - master
